

// Copyright 2008-2009 Emilio Lopez-Gabeiras
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//


// DO NOT EDIT, this class is autogenerated
// schema file: apb/schema.xml
// $Id$
package apb.test;

public class FieldNameProvider
{
    //~ Methods ..............................................................................................

    public static String OUs_ouIn()
    {
        return "ouIn";
    }

    public static String OUs_parentIn()
    {
        return "parentIn";
    }

    public static String OUs_name()
    {
        return "name";
    }

    public static String OUs_fullPathName()
    {
        return "fullPathName";
    }

    public static String Roles_roleIn()
    {
        return "roleIn";
    }

    public static String Roles_roleId()
    {
        return "roleId";
    }

    public static String Participants_participantIn()
    {
        return "participantIn";
    }

    public static String Participants_participantId()
    {
        return "participantId";
    }

    public static String Participants_ouIn()
    {
        return "ouIn";
    }

    public static String Participants_displayName()
    {
        return "displayName";
    }

    public static String Processes_ouIn()
    {
        return "ouIn";
    }

    public static String Processes_processIn()
    {
        return "processIn";
    }

    public static String Processes_processId()
    {
        return "processId";
    }

    public static String Processes_label()
    {
        return "label";
    }

    public static String Activities_activityIn()
    {
        return "activityIn";
    }

    public static String Activities_activityId()
    {
        return "activityId";
    }

    public static String Activities_processIn()
    {
        return "processIn";
    }

    public static String Activities_label()
    {
        return "label";
    }

    public static String Workload_snapshotTime()
    {
        return "snapshotTime";
    }

    public static String Workload_activityIn()
    {
        return "activityIn";
    }

    public static String Workload_roleIn()
    {
        return "roleIn";
    }

    public static String Workload_participantIn()
    {
        return "participantIn";
    }

    public static String Workload_origActivityIn()
    {
        return "origActivityIn";
    }

    public static String Workload_waitActivityIn()
    {
        return "waitActivityIn";
    }

    public static String Workload_quantity()
    {
        return "quantity";
    }

    public static String Workload_avgTimeTask()
    {
        return "avgTimeTask";
    }

    public static String Workload_avgTimeProcess()
    {
        return "avgTimeProcess";
    }

    public static String Workload_meanTimeTask()
    {
        return "meanTimeTask";
    }

    public static String Workload_meanTimeProcess()
    {
        return "meanTimeProcess";
    }

    public static String TaskPerformance_activityIn()
    {
        return "activityIn";
    }

    public static String TaskPerformance_roleIn()
    {
        return "roleIn";
    }

    public static String TaskPerformance_participantIn()
    {
        return "participantIn";
    }

    public static String TaskPerformance_completionDate()
    {
        return "completionDate";
    }

    public static String TaskPerformance_taskTime()
    {
        return "taskTime";
    }

    public static String TaskPerformance_idleTime()
    {
        return "idleTime";
    }

    public static String ProcessPerformance_processIn()
    {
        return "processIn";
    }

    public static String ProcessPerformance_completionDate()
    {
        return "completionDate";
    }

    public static String ProcessPerformance_taskTime()
    {
        return "taskTime";
    }

    public static String Checkpoints_engineId()
    {
        return "engineId";
    }

    public static String Checkpoints_loadTime()
    {
        return "loadTime";
    }

    public static String Checkpoints_status()
    {
        return "status";
    }

    public static String LastSnapshot_updaterId()
    {
        return "updaterId";
    }

    public static String LastSnapshot_lastSnapshotTime()
    {
        return "lastSnapshotTime";
    }

    public static String migration_build()
    {
        return "build";
    }

    public static String migration_description()
    {
        return "description";
    }
}
// End of FieldNameProvider.java
