

// Copyright 2008-2009 Emilio Lopez-Gabeiras
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//


// DO NOT EDIT, this class is autogenerated
// schema file: apb/schema.xml
// $Id$
package apb.test;

public class TableNameProvider
{
    //~ Methods ..............................................................................................

    public static String OUs()
    {
        return "OUs";
    }

    public static String Roles()
    {
        return "Roles";
    }

    public static String Participants()
    {
        return "Participants";
    }

    public static String Processes()
    {
        return "Processes";
    }

    public static String Activities()
    {
        return "Activities";
    }

    public static String Workload()
    {
        return "Workload";
    }

    public static String TaskPerformance()
    {
        return "TaskPerformance";
    }

    public static String ProcessPerformance()
    {
        return "ProcessPerformance";
    }

    public static String Checkpoints()
    {
        return "Checkpoints";
    }

    public static String LastSnapshot()
    {
        return "LastSnapshot";
    }

    public static String migration()
    {
        return "migration";
    }
}
// End of TableNameProvider.java
