
// DO NOT EDIT, this class is autogenerated 
// schema file: apb/schema.xml
// $Id$    
package apb.test;

public class TableNameProvider
{

    public static String OUs()
    {
	return "OUs";
    }

    public static String Roles()
    {
	return "Roles";
    }

    public static String Participants()
    {
	return "Participants";
    }

    public static String Processes()
    {
	return "Processes";
    }

    public static String Activities()
    {
	return "Activities";
    }

    public static String Workload()
    {
	return "Workload";
    }

    public static String TaskPerformance()
    {
	return "TaskPerformance";
    }

    public static String ProcessPerformance()
    {
	return "ProcessPerformance";
    }

    public static String Checkpoints()
    {
	return "Checkpoints";
    }

    public static String LastSnapshot()
    {
	return "LastSnapshot";
    }

    public static String migration()
    {
	return "migration";
    }

}
// End of TableNameProvider.java
