<?xml version='1.0'?>
<!--
$Id$
 -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"
    xmlns:date="http://exslt.org/dates-and-times"
    >
<xsl:param name="file" select="schema.xml"/>
<xsl:param name="package" />
<xsl:template match="text()">
	      <xsl:value-of select="normalize-space()"/>
</xsl:template>
<xsl:template match="/">
// DO NOT EDIT, this class is autogenerated 
// schema file: <xsl:value-of select="$file"/>
// $Id$    
package <xsl:value-of select="$package"/>;

public class TableNameProvider
{
<xsl:apply-templates/>
}
// End of TableNameProvider.java
</xsl:template>
<xsl:template match="/Schema/table">
    public static String <xsl:choose><xsl:when test="string-length(@real)>0"><xsl:value-of select="./@real"/></xsl:when><xsl:otherwise><xsl:value-of select="./@name"/></xsl:otherwise></xsl:choose>()
    {
	return "<xsl:value-of select="./@name"/>";
    }
</xsl:template>
</xsl:stylesheet>

